pastes/urls.py
from django.conf.urls import url

from . import views

app_name='pastes'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^save$', views.save, name='save'),
	url(r'^show/(.*)$', views.show, name='show'),
	url(r'^authenticate$', views.authenticate, name='authenticate')
]

scribbles/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('pastes.urls')),
]

pastes/models.py
from django.db import models

class Paste(models.Model):
	content = models.TextField()
	pub_date = models.DateTimeField('date published')
	is_private = models.BooleanField(default=True)
	token = models.CharField(max_length=40, primary_key=True)
	password = models.CharField(max_length=60, default='')

	def __str__(self):
		return self.token + ": " + self.content

pastes/views.py
import bcrypt
import uuid

from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.utils import timezone

from .models import Paste

def index(request):
    context = {}
    return render(request, 'pastes/index.html', context)

def save(request):
    uid = uuid.uuid4()
    token = uid.hex
    while Paste.objects.filter(token=token).exists():
        uid = uuid.uuid4()
        token = uid.hex

    posted_content = request.POST['content']

    is_private = False
    if 'isPrivate' in request.POST:
        is_private = True

    password = request.POST['pwd']
    hashed = ""
    if len(password) > 0:
        hashed = bcrypt.hashpw(password, bcrypt.gensalt())

    p = Paste(content=posted_content, pub_date=timezone.now(), 
        is_private=is_private, token=token, password=hashed)
    p.save()

    return HttpResponseRedirect('show/' + token)

def show(request, token, authFailure=False):  

    try:   
        paste = Paste.objects.get(pk=token)
    except Paste.DoesNotExist:
        return render(request, 'pastes/no_such_paste.html')

    if len(paste.password) > 0:
        context = {'token': token, 'authFailure': authFailure}
        return render(request, 'pastes/password_protected.html', context)
    
    return show_without_password_check(request, paste)

def show_without_password_check(request, paste):
    context = {'paste': paste}    
    return render(request, 'pastes/show.html', context)

def authenticate(request):
    password = request.POST['pwd']
    token = request.POST['token']

    paste = Paste.objects.get(pk=token)

    if bcrypt.hashpw(password, paste.password) == paste.password:
        return show_without_password_check(request, paste)

    return show(request, token, authFailure=True)

pastes/templates/pastes/base.html
{% load staticfiles %}
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		{% block robots_meta %}{% endblock %}
		<title>Scribbles {% block page_title %}{% endblock %}</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link href="https://fonts.googleapis.com/css?family=Just+Another+Hand" rel="stylesheet">
		<script src="https://use.fontawesome.com/739b6e2063.js"></script>
		<link rel="stylesheet" href="{% static 'css/pastes.css' %}">
	</head>
	<body>
		<h3 class="scribbles_logo"><a href="/" title="Scribbles Home">SCRIBBLES&nbsp;  <i class="fa fa-pencil" aria-hidden="true"></i></a></h3>
		<section>
		{% block content %}
		{% endblock %}
		</section>
	</body>
</html>

pastes/templates/pastes/index.html
{% extends 'pastes/base.html' %}


{% block page_title %}
	- New
{% endblock %}


{% block content %}

<form action="{% url 'pastes:save' %}" method="post">
	{% csrf_token %}
	<div>
		<textarea class="scribbles_content_box" name="content"></textarea>
	</div>

	<div class="form_controls">
		<div class="fcontrol">
			<input id="isPrivate" type="checkbox" name="isPrivate" /> <label for="isPrivate">Set as Private</label>
		</div>	
		<div class="fcontrol">
			<label for="pwd">Password (Optional):</label> <input type="password" id="pwd" name="pwd" />
		</div>
		<div class="fcontrol">
			<input type="submit" value="Submit" class="scribbles_submit btn btn-primary" />
		</div>	
	</div>
<form>	

{% endblock %}

pastes/templates/pastes/no_such_paste.html
{% extends 'pastes/base.html' %}

{% block content %}

<h3>Oops! The scribble you're trying to view does not exist or has been deleted.</h3>

{% endblock %}

pastes/templates/pastes/password_protected.html
{% extends 'pastes/base.html' %}

{% block content %}

<p>The scribble you're trying to view is password protected. Please enter the password below</p>
<p class="error">{% if authFailure %}Error: Incorrect Password. Try again. {% endif %}</p>
<form action="{% url 'pastes:authenticate' %}" method="post">
	{% csrf_token %}
	<label for="pwd">Password:</label> <input type="password" name="pwd" id="pwd" />
	<input type="hidden" name="token" value="{{token}}" />
	<input type="submit" class="btn btn-primary" />
<form>	

{% endblock %}

pastes/templates/pastes/show.html
{% extends 'pastes/base.html' %}

{% block robots_meta %}
	{% if paste.is_private %}
		<meta name="robots" content="noindex, nofollow">
	{% endif %}
{% endblock %}

{% block content %}

	<div class="permalink">
		Permalink: <a href="/show/{{paste.token}}" alt="Permalink" />{{request.META.HTTP_HOST}}/show/{{paste.token}}</a>
	</div>

	<pre>{{paste.content}}</pre>

{% endblock %}